# Generated by Django 5.2.4 on 2025-07-24 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('ADD', 'Soma'), ('SUB', 'Subtração'), ('MUL', 'Multiplicação'), ('DIV', 'Divisão')], max_length=3)),
                ('a', models.DecimalField(decimal_places=6, max_digits=20)),
                ('b', models.DecimalField(decimal_places=6, max_digits=20)),
                ('expression', models.CharField(max_length=255)),
                ('result', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
